### ISSUE TITLE
Browser preview reloads but does not update

### ISSUE THREAD

**Issue by imrehg** [balena-io/resin-emails#4]
When using `npm start` and viewing the email in the browser, the page does do a reload on file change, but it still displays the previous version (and Shift-F5 reload doesn't update to the new version either). Have to stop and do another `npm start` apparently. Chromium 56.0.2924.76 (Linux 64-bit)

**Comment by craig-mulligan** [comment]
@imrehg were you editing a data file? See the readme we were waiting on this [PR](https://github.com/zurb/panini/pull/82/commits/47173300605f49ee7372324ada229a28500ba871), but I see it's merged so we probably just need a version bump.

**Comment by dansku** [comment]
Developed the last version and looks like everything was working. This issue is almost one year old, so I am closing it.
